waste_segregation_app/urls.py
from django.urls import path
from . import views

app_name = 'waste_segregation_app'
urlpatterns = [
    path('', views.new_trash, name='new_trash'),
    path('bin/', views.check_bin, name='bin'),
]

waste_segregation_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("waste_segregation_app.urls")),
]

waste_segregation_app/models.py
from django.db import models

bins = { 
    'yellow': ['plastic', 'carton of milk', 'carton of juice', 'tin', 'bottle cap', 'metal'],
    'blue' : ['newspaper', 'book', 'paper', 'cardboard'],
    'green' : ['glass'],
    'black' : ['sponge', 'cloth', 'meat', 'fish', 'poo', 'oil', 'dust', 'china', 'diaper', 'sanitary towel', 'cotton wool', 'leather', 'tea bag', 'hair'],
    'pharmacy' : ['medicinie', 'drug', 'pill'],
    'brown' : ['grass', 'flowers']
}

# Create your models here.
class Trash(models.Model):
    trash_description = models.CharField(max_length=20)
    
    class Meta:
        verbose_name_plural = 'trash'
    
    def __str__(self):
        return self.trash_description
    
    def check_bin(self):
        trash_description = self.trash_description.lower()
        for bin in bins:
            if trash_description in bins.get(bin): 
                    return bin
            for trash in trash_description.split(): 
                if trash in bins.get(bin):
                    return bin
        return 'Unknown'
    

waste_segregation_app/forms.py
from django import forms

from .models import Trash

class TrashForm(forms.ModelForm):
    class Meta:
        model = Trash
        fields = ['trash_description']
        label = {'trash_description':''}

waste_segregation_app/views.py
from django.shortcuts import render, redirect

from .models import Trash
from .forms import TrashForm
# Create your views here.

def new_trash(request):
    if request.method != 'POST':
        form = TrashForm()
    else:
        form = TrashForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('waste_segregation_app:bin')
    context = {'form': form}
    return render(request, 'waste_segregation_app/new_trash.html', context)

def check_bin(request):
    trash = Trash.objects.last()
    bin = trash.check_bin()
    
    context = {'bin':bin}
    return render (request, 'waste_segregation_app/bin.html', context)
    

waste_segregation_app/templates/waste_segregation_app/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1,
  shrink-to-fit=no">
  <title>Let's segregate</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
<div class="p-3 mb-2 bg-primary text-white text-center"><h1>Let's segregate!</h1></div>

<main role="main" class="container">
    <div class="pb-1 mb-2 border-bottom">
         {% block page_header %}{% endblock page_header %}
    </div>
    <div>
         {% block content %}{% endblock content %}
    </div>
</main>

</body>

</html>

waste_segregation_app/templates/waste_segregation_app/bin.html
{% extends "waste_segregation_app/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h3>Your bin:</h3>
{% endblock page_header %}

{% block content %}

{{bin}}

{% endblock content %}

waste_segregation_app/templates/waste_segregation_app/new_trash.html
{% extends "waste_segregation_app/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Descibe your trash</h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'waste_segregation_app:new_trash' %}" method = 'post'>
    {% csrf_token %}
    <form>
    <label for="trash_description">Trash name</label>
    <input type="text" class="form-control" id="trash_description" placeholder="plastic bottle, tea bag" name="trash_description"><br>
    <button type="submit" class="btn btn-primary mb-2">Check</button>
    </form>
</form>

{% endblock content %}